# Generated by Django 3.2 on 2021-05-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_background',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default_img.png', upload_to='uploads/profile_background'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='uploads/profile_background/default_img.png', upload_to='uploads/profile_pictures'),
        ),
    ]
